export const ROUTES = {
  dashboard: '/',
  recipes: '/recipes',
  providers: '/providers',
  supplies: '/supplies',
  reports: '/reports',
  users: '/users',
  perfils: '/perfils',
  ciudads: '/ciudads',
  departamentos: '/departamentos',
  categorias: '/categorias',
  comedors: '/comedors',
  unidadesMedida: '/unidades-medida',
  planes: '/planes',
  ordenesCompra: '/ordenes-compra',
  ordenCompraItems: '/orden-compra-items',
  auditoriaEventos: '/auditoria-eventos',
  reporteCostosCrud: '/reporte-costos',
  profile: '/profile',
  login: '/login',
  register: '/register',
}
